### ISSUE TITLE
Sometimes the background show different colors blocks

### ISSUE THREAD

**Issue by davidcostadev** [wavebeem/vscode-theme-unoduetre#6]
### Previews

![Screenshot from 2020-01-26 21-54-18](https://user-images.githubusercontent.com/3098556/73144649-a36f5800-4086-11ea-920b-82fa4fe9201b.png)
![Screenshot from 2020-01-26 21-56-12](https://user-images.githubusercontent.com/3098556/73144653-ad915680-4086-11ea-8376-7d872b92521b.png)

This problem is happening on Mac OS and Ubuntu

**Comment by wavebeem** [comment]
Both macOS and Ubuntu? That's odd. Given the shapes and colors, I think this is an error with Visual Studio Code, or perhaps your graphics drivers or computer.

I have seen similar issues that were ultimately Electron bugs that got fixed with a later Code update.

I don't think there's anything I can do to help.

I hope this gets fixed for you soon.

**Comment by davidcostadev** [comment]
Okay, :-(. Thanks for the quick answer.

**Comment by wavebeem** [comment]
I suppose I should've asked---can you replicate this issue with other color schemes? Either way, I think you might want to file a bug against the VS Code repo. I hope the issue gets fixed soon. I was very annoyed when I had a similar bug.

And thanks for using my theme 😄

**Comment by davidcostadev** [comment]
Yes, you are correct, probably this is a bug of vscode.

You are welcome, I love your theme so much!

https://youtu.be/EhAM4l0cH3U

![Screenshot from 2020-01-26 22-12-50](https://user-images.githubusercontent.com/3098556/73144964-6e183980-4089-11ea-8906-ed0a14fd3af9.png)
